server {
    listen 3000;
    server_name _;
    root /home/setyanet/setya-abadi-elektronik/apps/web/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Deny access to hidden files
    location ~ /\. {
        deny all;
    }
}
